// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'shiro', 'shadow', 'helena', 'poonam', 'clemens', 'weckner', 'camino', 'camino-night', 'lavender', 'bubblegum', 'hecker', 'peach', 'ember', 'ocean', 'navy', 'sakura', 'slate', 'kela']
    }
}

export {}
