// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'navy', 'sakura', 'forest', 'lavender', 'ember', 'ocean', 'slate', 'peach', 'kela', 'hecker', 'bubblegum']
    }
}

export {}
