"""Compile editable Shiro SVG layers into Metro-friendly Skia path data.

Run from any directory with python3. No third-party Python packages required.
"""
import json
from pathlib import Path
import xml.etree.ElementTree as ET

MOBILE = Path(__file__).resolve().parents[2]
ART = MOBILE / "assets/images/shiro-dog-vector"
NS = "{http://www.w3.org/2000/svg}"
ET.register_namespace("", NS[1:-1])
rest = ET.parse(ART / "resting.svg").getroot()
front = ET.parse(ART / "front.svg").getroot()
middle = ET.parse(ART / "three-quarter.svg").getroot()


def group(root, name):
    return next(e for e in root.iter() if e.get("id") == name)


def layer(names):
    shapes = []
    inherited = {**rest.attrib, **rest.find(NS + "g").attrib}
    def visit(element, parent):
        attrs = {**parent, **element.attrib}
        if element.tag == NS + "path":
            shapes.append({
                "path": attrs["d"], "fill": attrs.get("fill", "none"),
                "stroke": attrs.get("stroke", "none"),
                "strokeWidth": float(attrs.get("stroke-width", 1)),
                "opacity": float(attrs.get("opacity", 1)),
            })
        else:
            for child in element:
                visit(child, attrs)
    for name in names:
        visit(group(rest, name), inherited)
    return shapes


data = {
    "body": layer(["far-foreleg", "body", "near-foreleg", "front-right-paw", "haunch-and-hind-paw"]),
    "tail": layer(["tail"]),
    "collar": layer(["collar"]),
    "rest": {},
    "middle": {},
    "front": {},
    "gradients": {},
}
for gradient in rest.find(NS + "defs"):
    data["gradients"][gradient.get("id")] = {
        "start": [float(gradient.get("x1")), float(gradient.get("y1"))],
        "end": [float(gradient.get("x2")), float(gradient.get("y2"))],
        "colors": [stop.get("stop-color") for stop in gradient],
        "positions": [float(stop.get("offset", 0)) for stop in gradient],
    }
for name, root in [("rest", rest), ("middle", middle), ("front", front)]:
    for key, group_id, index in [
        ("head", "head-base", 0), ("tuft", "head-base", 1),
        ("earFill", "near-ear", 0), ("earLine", "near-ear", 1),
        ("nose", "nose", 0), ("brow", "brow", 0),
    ]:
        data[name][key] = group(root, group_id)[index].get("d")
    if name != "rest":
        data[name]["farEar"] = group(root, "far-ear")[0].get("d")
        data[name]["smile"] = group(root, "mouth")[0].get("d")
        for key, group_id in [("eye", "visible-eye"), ("farEye", "far-eye")]:
            eye = group(root, group_id)[0]
            data[name][key] = [float(eye.get(k)) for k in ["cx", "cy", "rx", "ry"]]
target = MOBILE / "src/components/backdrops/shiro-art.generated.ts"
target.write_text(
    "// Generated by scripts/art/generate-shiro-art.py. Edit the source SVGs.\n"
    "export const SHIRO_ART = " + json.dumps(data, indent=2) + " as const;\n"
)
print(f"Generated {target.relative_to(MOBILE)}")
