"""Compile Shadow's named SVG layers to Skia drawing data (standard library only)."""
import json
import re
import xml.etree.ElementTree as E
from pathlib import Path
MOBILE=Path(__file__).resolve().parents[2]
ART=MOBILE/'assets/images/shadow-cat-vector'
N='{http://www.w3.org/2000/svg}'
def read(name):
 root=E.parse(ART/name).getroot()
 def visit(e,parent):
  a={**parent,**e.attrib};tag=e.tag.split('}')[-1]
  if tag not in ['g','path','ellipse']:return None
  node={'tag':tag,'id':e.get('id','')}
  if tag=='g':
   node['children']=[v for c in e if (v:=visit(c,a))]
   if 'clip-path' in e.attrib:node['clip']=e.get('clip-path')[5:-1]
  else:
   node.update({k:a.get(k,default) for k,default in [('fill','none'),('stroke','none'),('stroke-width','1'),('opacity','1')]})
   if tag=='path':
    node['d']=a['d']
    if a.get('id') == 'tail' or parent.get('id') == 'tail':
     def deform(amount):
      values=list(map(float, re.findall(r'-?\d+(?:\.\d+)?', a['d'])))
      for i in range(0,len(values),2):
       weight=max(0,min(1,(values[i+1]-1240)/240))
       values[i]+=amount*weight*weight
      it=iter(values)
      return re.sub(r'-?\d+(?:\.\d+)?',lambda m: str(next(it)),a['d'])
     node['tailLeft']=deform(-90)
     node['tailRight']=deform(90)
   else:
    node.update({k:float(a[k]) for k in ['cx','cy','rx','ry']})
    node['angle']=float(a.get('transform','rotate(0').split('(')[1].split()[0])
  return node
 groups={e.get('id'):visit(e,root.attrib) for e in root if e.tag==N+'g'}
 return {'groups':groups,'clips':{e.get('id'):e[0].get('d') for e in root.find(N+'defs') if e.tag==N+'clipPath'}}
root=E.parse(ART/'resting.svg').getroot();gradients={}
for e in root.find(N+'defs'):
 if e.tag!=N+'linearGradient':continue
 gradients[e.get('id')]={'start':[float(e.get('x1')),float(e.get('y1'))],'end':[float(e.get('x2')),float(e.get('y2'))],'colors':[s.get('stop-color') for s in e],'positions':[float(s.get('offset',0)) for s in e]}
# The unnamed outer group contains the articulated layers.
data={'rest':read('resting.svg'),'middle':read('transition.svg'),'front':read('front.svg'),'gradients':gradients}
target=MOBILE/'src/components/backdrops/shadow-art.generated.ts'
target.write_text('// Generated by scripts/art/generate-shadow-art.py. Edit source SVGs.\nexport const SHADOW_ART = '+json.dumps(data,indent=2)+' as const;\n')
