// Package-root imports register every font variant with Metro, even unused ones.
import { Inter_400Regular } from '@expo-google-fonts/inter/400Regular';
import { Inter_500Medium } from '@expo-google-fonts/inter/500Medium';
import { Inter_600SemiBold } from '@expo-google-fonts/inter/600SemiBold';
import { Inter_700Bold } from '@expo-google-fonts/inter/700Bold';
import { JetBrainsMono_400Regular } from '@expo-google-fonts/jetbrains-mono/400Regular';
import { JetBrainsMono_500Medium } from '@expo-google-fonts/jetbrains-mono/500Medium';
import { JetBrainsMono_600SemiBold } from '@expo-google-fonts/jetbrains-mono/600SemiBold';
import { JetBrainsMono_700Bold } from '@expo-google-fonts/jetbrains-mono/700Bold';

// Title fonts are vendored copies with patched vertical metrics
// (assets/fonts/, generated by scripts/patch-font-metrics.py). The originals
// declare padded ascent/descent spans that make Android's line-box math clip
// descenders at heading line heights — see HEADING_FONT_METRICS in
// ./typography.ts. Their @expo-google-fonts packages stay installed as the
// patch script's source of truth; don't import the title faces from them.
const Baskervville_700Bold: number = require('../../../assets/fonts/Baskervville_700Bold.ttf');
const Figtree_700Bold: number = require('../../../assets/fonts/Figtree_700Bold.ttf');
const Cinzel_700Bold: number = require('../../../assets/fonts/Cinzel_700Bold.ttf');
const GloriaHallelujah_400Regular: number = require('../../../assets/fonts/GloriaHallelujah_400Regular.ttf');
const Lora_700Bold: number = require('../../../assets/fonts/Lora_700Bold.ttf');
const SpaceMono_700Bold: number = require('../../../assets/fonts/SpaceMono_700Bold.ttf');

export const APP_FONT_ASSETS = {
  Baskervville_700Bold,
  Figtree_700Bold,
  Cinzel_700Bold,
  GloriaHallelujah_400Regular,
  Lora_700Bold,
  SpaceMono_700Bold,
  Inter_400Regular,
  Inter_500Medium,
  Inter_600SemiBold,
  Inter_700Bold,
  JetBrainsMono_400Regular,
  JetBrainsMono_500Medium,
  JetBrainsMono_600SemiBold,
  JetBrainsMono_700Bold,
} as const;
