export const TITLE_FONTS = [
  {
    id: 'figtree',
    label: 'Figtree',
    fontFamily: 'Figtree_700Bold',
  },
  {
    id: 'lora',
    // The bundled file is metric-patched (scripts/patch-font-metrics.py), and
    // its internal name table is renamed to honor Lora's OFL Reserved Font
    // Name at the font-software level. The picker label deliberately stays
    // "Lora": the face is Lora with whitespace-only metric tweaks, and an
    // invented name would misattribute the design (decision 2026-07-24).
    label: 'Lora',
    fontFamily: 'Lora_700Bold',
  },
  {
    id: 'gloriahallelujah',
    label: 'Gloria Hallelujah',
    fontFamily: 'GloriaHallelujah_400Regular',
  },
  {
    id: 'cinzel',
    label: 'Cinzel',
    fontFamily: 'Cinzel_700Bold',
  },
  {
    id: 'spacemono',
    label: 'Space Mono',
    fontFamily: 'SpaceMono_700Bold',
  },
  {
    id: 'baskervville',
    label: 'Baskervville',
    fontFamily: 'Baskervville_700Bold',
  },
] as const;

export type TitleFontId = (typeof TITLE_FONTS)[number]['id'];

export const BODY_FONT_PACKS = {
  inter: {
    '--font-body': 'Inter_400Regular',
    '--font-body-medium': 'Inter_500Medium',
    '--font-body-semibold': 'Inter_600SemiBold',
    '--font-body-bold': 'Inter_700Bold',
  },
  jetbrainsMono: {
    '--font-body': 'JetBrainsMono_400Regular',
    '--font-body-medium': 'JetBrainsMono_500Medium',
    '--font-body-semibold': 'JetBrainsMono_600SemiBold',
    '--font-body-bold': 'JetBrainsMono_700Bold',
  },
} as const;

export type BodyFontPackId = keyof typeof BODY_FONT_PACKS;

export const THEME_TOKEN_KEYS = [
  '--color-background',
  '--color-foreground',
  '--color-card',
  '--color-card-foreground',
  '--color-popover',
  '--color-popover-foreground',
  '--color-primary',
  '--color-primary-foreground',
  '--color-secondary',
  '--color-secondary-foreground',
  '--color-muted',
  '--color-muted-foreground',
  '--color-accent',
  '--color-accent-foreground',
  '--color-destructive',
  '--color-destructive-foreground',
  '--color-border',
  '--color-input',
  '--color-ring',
  '--color-active-overlay',
  '--theme-radius',
  '--theme-border-width',
  '--theme-shadow',
] as const;

export const FONT_TOKEN_KEYS = [
  '--font-heading',
  '--font-body',
  '--font-body-medium',
  '--font-body-semibold',
  '--font-body-bold',
] as const;

export const REQUIRED_THEME_VARIABLES = [
  ...THEME_TOKEN_KEYS,
  ...FONT_TOKEN_KEYS,
] as const;

export type ThemeTokenKey = (typeof THEME_TOKEN_KEYS)[number];
export type ThemeVariant = 'light' | 'dark';

export type ThemeTokenValues = Record<ThemeTokenKey, string>;

export const DEFAULT_THEME_ID = 'light' as const;
export const DEFAULT_TITLE_FONT = 'figtree' as const satisfies TitleFontId;

export const THEME_DEFINITIONS = [
  {
    id: 'light',
    name: 'Light',
    description: 'Warm beige/olive (DEFAULT)',
    variant: 'light',
    enableTimelineBorders: false,
    defaultTitleFontId: 'figtree',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#e4d7b0',
      '--color-foreground': '#44362c',
      '--color-card': '#e7dbbf',
      '--color-card-foreground': '#44362c',
      '--color-popover': '#f3ead2',
      '--color-popover-foreground': '#44362c',
      '--color-primary': '#c2af5d',
      '--color-primary-foreground': '#44362c',
      '--color-secondary': '#decea0',
      '--color-secondary-foreground': '#44362c',
      '--color-muted': '#decea0',
      '--color-muted-foreground': '#85766a',
      '--color-accent': '#dbc894',
      '--color-accent-foreground': '#44362c',
      '--color-destructive': '#b5766a',
      '--color-destructive-foreground': '#faf8f2',
      '--color-border': '#b19681',
      '--color-input': '#dbc894',
      '--color-ring': '#9db18c',
      '--color-active-overlay': 'rgba(0, 0, 0, 0.12)',
      '--theme-radius': '8px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.15)',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'Earthy dark (DEFAULT DARK)',
    variant: 'dark',
    enableTimelineBorders: false,
    defaultTitleFontId: 'figtree',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#3a3529',
      '--color-foreground': '#ede4d4',
      '--color-card': '#413c33',
      '--color-card-foreground': '#ede4d4',
      '--color-popover': '#413c33',
      '--color-popover-foreground': '#ede4d4',
      '--color-primary': '#6a755a',
      '--color-primary-foreground': '#ede4d4',
      '--color-secondary': '#5a5345',
      '--color-secondary-foreground': '#ede4d4',
      '--color-muted': '#4a4439',
      '--color-muted-foreground': '#a8a096',
      '--color-accent': '#a18f5c',
      '--color-accent-foreground': '#2a2521',
      '--color-destructive': '#b5766a',
      '--color-destructive-foreground': '#faf8f2',
      '--color-border': '#5a5345',
      '--color-input': '#5a5345',
      '--color-ring': '#8a9f7b',
      '--color-active-overlay': 'rgba(255, 255, 255, 0.12)',
      '--theme-radius': '8px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.4)',
    },
  },
  {
    id: 'lavender',
    name: 'Lavender',
    description: 'Gentle purple/lavender',
    variant: 'light',
    enableTimelineBorders: false,
    defaultTitleFontId: 'gloriahallelujah',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#f3eef8',
      '--color-foreground': '#2e2440',
      '--color-card': '#f8f4fc',
      '--color-card-foreground': '#2e2440',
      '--color-popover': '#faf7fd',
      '--color-popover-foreground': '#2e2440',
      '--color-primary': '#bea8e5',
      '--color-primary-foreground': '#2e2440',
      '--color-secondary': '#e0d4f0',
      '--color-secondary-foreground': '#2e2440',
      '--color-muted': '#e0d4f0',
      '--color-muted-foreground': '#6e5a8a',
      '--color-accent': '#d0c0e4',
      '--color-accent-foreground': '#2e2440',
      '--color-destructive': '#b84060',
      '--color-destructive-foreground': '#f8f4fc',
      '--color-border': '#c8b8dc',
      '--color-input': '#d0c0e4',
      '--color-ring': '#9b7bc7',
      '--color-active-overlay': 'rgba(0, 0, 0, 0.12)',
      '--theme-radius': '8px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.15)',
    },
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    description: 'Neo-Brutalism Pop',
    variant: 'light',
    enableTimelineBorders: true,
    defaultTitleFontId: 'spacemono',
    bodyFontPackId: 'jetbrainsMono',
    tokens: {
      '--color-background': '#ffc4e1',
      '--color-foreground': '#000000',
      '--color-card': '#ffffff',
      '--color-card-foreground': '#000000',
      '--color-popover': '#ffffff',
      '--color-popover-foreground': '#000000',
      '--color-primary': '#ff3d9e',
      '--color-primary-foreground': '#000000',
      '--color-secondary': '#00ffcc',
      '--color-secondary-foreground': '#000000',
      '--color-muted': '#ffe8f2',
      '--color-muted-foreground': '#4a4a4a',
      '--color-accent': '#faff00',
      '--color-accent-foreground': '#000000',
      '--color-destructive': '#cf382d',
      '--color-destructive-foreground': '#ffffff',
      '--color-border': '#000000',
      '--color-input': '#ffffff',
      '--color-ring': '#000000',
      '--color-active-overlay': 'rgba(0, 0, 0, 0.2)',
      /* MUST be exactly '0' (not '0px') for React logic string matching */
      '--theme-radius': '0',
      '--theme-border-width': '3px',
      '--theme-shadow': '4px 4px 0px 0px rgba(0, 0, 0, 1)',
    },
  },
  {
    id: 'clemens',
    name: 'Clemens',
    description: 'Soft sage/botanical calm',
    variant: 'light',
    enableTimelineBorders: false,
    backdropId: 'botanical',
    defaultTitleFontId: 'baskervville',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#dde8d8',
      '--color-foreground': '#243428',
      '--color-card': '#e7efe0',
      '--color-card-foreground': '#243428',
      '--color-popover': '#eff4e9',
      '--color-popover-foreground': '#243428',
      '--color-primary': '#9dbf90',
      '--color-primary-foreground': '#243428',
      '--color-secondary': '#cdddc4',
      '--color-secondary-foreground': '#243428',
      '--color-muted': '#cdddc4',
      '--color-muted-foreground': '#5d7360',
      '--color-accent': '#d3c48f',
      '--color-accent-foreground': '#3a3320',
      '--color-destructive': '#b05a48',
      '--color-destructive-foreground': '#f3f6ee',
      '--color-border': '#a4bb9a',
      '--color-input': '#c3d6b9',
      '--color-ring': '#5e8a63',
      '--color-active-overlay': 'rgba(36, 52, 40, 0.1)',
      '--theme-radius': '12px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(38, 56, 42, 0.14)',
    },
  },
  {
    id: 'weckner',
    name: 'Weckner',
    description: 'Forest dusk/brass lamplight',
    variant: 'dark',
    enableTimelineBorders: false,
    backdropId: 'botanical',
    defaultTitleFontId: 'baskervville',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#16211a',
      '--color-foreground': '#d7e3d2',
      '--color-card': '#1d2a21',
      '--color-card-foreground': '#d7e3d2',
      '--color-popover': '#233129',
      '--color-popover-foreground': '#d7e3d2',
      '--color-primary': '#6c9260',
      '--color-primary-foreground': '#eef4e9',
      '--color-secondary': '#2a3a2e',
      '--color-secondary-foreground': '#d7e3d2',
      '--color-muted': '#243027',
      '--color-muted-foreground': '#8ba18c',
      '--color-accent': '#ab9459',
      '--color-accent-foreground': '#f0e9d6',
      '--color-destructive': '#b5584a',
      '--color-destructive-foreground': '#f3f6ee',
      '--color-border': '#2f4033',
      '--color-input': '#2a3a2e',
      '--color-ring': '#7ba26f',
      '--color-active-overlay': 'rgba(215, 227, 210, 0.1)',
      '--theme-radius': '12px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.45)',
    },
  },
  {
    id: 'hecker',
    name: 'Hecker',
    description: 'Cyberpunk/Retro-Futurism',
    variant: 'dark',
    enableTimelineBorders: true,
    defaultTitleFontId: 'spacemono',
    bodyFontPackId: 'jetbrainsMono',
    tokens: {
      '--color-background': '#000000',
      '--color-foreground': '#00ff41',
      '--color-card': '#050505',
      '--color-card-foreground': '#00ff41',
      '--color-popover': '#0a0a0a',
      '--color-popover-foreground': '#00ff41',
      '--color-primary': '#0ac220',
      '--color-primary-foreground': '#d8e0f0',
      '--color-secondary': '#002200',
      '--color-secondary-foreground': '#00ff41',
      '--color-muted': '#0a0a0a',
      '--color-muted-foreground': '#0ac220',
      '--color-accent': '#002200',
      '--color-accent-foreground': '#00ff41',
      '--color-destructive': '#ff003c',
      '--color-destructive-foreground': '#ffffff',
      '--color-border': '#00ff41',
      '--color-input': '#050505',
      '--color-ring': '#00ff41',
      '--color-active-overlay': 'rgba(0, 255, 65, 0.15)',
      /* MUST be exactly '0' (not '0px') for React logic string matching */
      '--theme-radius': '0',
      '--theme-border-width': '2px',
      '--theme-shadow': '0px 0px 8px 0px rgba(0, 255, 65, 0.4)',
    },
  },
  {
    id: 'peach',
    name: 'Peach',
    description: 'Warm peach/coral pastels',
    variant: 'light',
    enableTimelineBorders: false,
    defaultTitleFontId: 'lora',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#fef0e8',
      '--color-foreground': '#3d2417',
      '--color-card': '#fff4ee',
      '--color-card-foreground': '#3d2417',
      '--color-popover': '#fff7f2',
      '--color-popover-foreground': '#3d2417',
      '--color-primary': '#f5aa8d',
      '--color-primary-foreground': '#3d2417',
      '--color-secondary': '#f4d0bc',
      '--color-secondary-foreground': '#3d2417',
      '--color-muted': '#f4d0bc',
      '--color-muted-foreground': '#8a6050',
      '--color-accent': '#ecc0a8',
      '--color-accent-foreground': '#3d2417',
      '--color-destructive': '#c44030',
      '--color-destructive-foreground': '#fff4ee',
      '--color-border': '#dcb0a0',
      '--color-input': '#ecc0a8',
      '--color-ring': '#e8845a',
      '--color-active-overlay': 'rgba(0, 0, 0, 0.12)',
      '--theme-radius': '8px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.15)',
    },
  },
  {
    id: 'ember',
    name: 'Ember',
    description: 'Warm charcoal/amber',
    variant: 'dark',
    enableTimelineBorders: false,
    defaultTitleFontId: 'cinzel',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#1a1210',
      '--color-foreground': '#f0d8c8',
      '--color-card': '#261c18',
      '--color-card-foreground': '#f0d8c8',
      '--color-popover': '#2e2420',
      '--color-popover-foreground': '#f0d8c8',
      '--color-primary': '#d4845a',
      '--color-primary-foreground': '#f0d8c8',
      '--color-secondary': '#382820',
      '--color-secondary-foreground': '#f0d8c8',
      '--color-muted': '#382820',
      '--color-muted-foreground': '#a08070',
      '--color-accent': '#443028',
      '--color-accent-foreground': '#f0d8c8',
      '--color-destructive': '#c44030',
      '--color-destructive-foreground': '#f0d8c8',
      '--color-border': '#443028',
      '--color-input': '#382820',
      '--color-ring': '#d4845a',
      '--color-active-overlay': 'rgba(255, 255, 255, 0.12)',
      '--theme-radius': '8px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.4)',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Coastal blues and sand',
    variant: 'light',
    enableTimelineBorders: false,
    defaultTitleFontId: 'cinzel',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#e8f1f5',
      '--color-foreground': '#1a3040',
      '--color-card': '#eef5f9',
      '--color-card-foreground': '#1a3040',
      '--color-popover': '#f2f8fb',
      '--color-popover-foreground': '#1a3040',
      '--color-primary': '#82bcda',
      '--color-primary-foreground': '#1a3040',
      '--color-secondary': '#c8dce8',
      '--color-secondary-foreground': '#1a3040',
      '--color-muted': '#c8dce8',
      '--color-muted-foreground': '#5a7888',
      '--color-accent': '#b0d0e0',
      '--color-accent-foreground': '#1a3040',
      '--color-destructive': '#c45040',
      '--color-destructive-foreground': '#eef5f9',
      '--color-border': '#a0c0d0',
      '--color-input': '#b0d0e0',
      '--color-ring': '#4a90b8',
      '--color-active-overlay': 'rgba(0, 0, 0, 0.12)',
      '--theme-radius': '8px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.15)',
    },
  },
  {
    id: 'navy',
    name: 'Navy',
    description: 'Deep navy/slate blue',
    variant: 'dark',
    enableTimelineBorders: false,
    defaultTitleFontId: 'cinzel',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#0f1729',
      '--color-foreground': '#d8e0f0',
      '--color-card': '#182038',
      '--color-card-foreground': '#d8e0f0',
      '--color-popover': '#1e2844',
      '--color-popover-foreground': '#d8e0f0',
      '--color-primary': '#6b8fd4',
      '--color-primary-foreground': '#d8e0f0',
      '--color-secondary': '#283858',
      '--color-secondary-foreground': '#d8e0f0',
      '--color-muted': '#283858',
      '--color-muted-foreground': '#7888a8',
      '--color-accent': '#304068',
      '--color-accent-foreground': '#d8e0f0',
      '--color-destructive': '#c45050',
      '--color-destructive-foreground': '#d8e0f0',
      '--color-border': '#304068',
      '--color-input': '#283858',
      '--color-ring': '#6b8fd4',
      '--color-active-overlay': 'rgba(255, 255, 255, 0.12)',
      '--theme-radius': '8px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.4)',
    },
  },
  {
    id: 'sakura',
    name: 'Sakura',
    description: 'Soft pink/cherry blossom',
    variant: 'light',
    enableTimelineBorders: false,
    defaultTitleFontId: 'figtree',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#fef1f3',
      '--color-foreground': '#4a2030',
      '--color-card': '#fff5f7',
      '--color-card-foreground': '#4a2030',
      '--color-popover': '#fff8f9',
      '--color-popover-foreground': '#4a2030',
      '--color-primary': '#f2a6b8',
      '--color-primary-foreground': '#4a2030',
      '--color-secondary': '#f8d5dc',
      '--color-secondary-foreground': '#4a2030',
      '--color-muted': '#f8d5dc',
      '--color-muted-foreground': '#8a5a6a',
      '--color-accent': '#f0c0cc',
      '--color-accent-foreground': '#4a2030',
      '--color-destructive': '#c44058',
      '--color-destructive-foreground': '#fff5f7',
      '--color-border': '#e8b0bc',
      '--color-input': '#f0c0cc',
      '--color-ring': '#e8829a',
      '--color-active-overlay': 'rgba(0, 0, 0, 0.12)',
      '--theme-radius': '8px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.15)',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    description: 'Neutral dark monochrome',
    variant: 'dark',
    enableTimelineBorders: false,
    defaultTitleFontId: 'gloriahallelujah',
    bodyFontPackId: 'inter',
    tokens: {
      '--color-background': '#18191c',
      '--color-foreground': '#d4d6dc',
      '--color-card': '#222428',
      '--color-card-foreground': '#d4d6dc',
      '--color-popover': '#2a2c32',
      '--color-popover-foreground': '#d4d6dc',
      '--color-primary': '#8890a0',
      '--color-primary-foreground': '#d4d6dc',
      '--color-secondary': '#303238',
      '--color-secondary-foreground': '#d4d6dc',
      '--color-muted': '#303238',
      '--color-muted-foreground': '#70747c',
      '--color-accent': '#3a3c44',
      '--color-accent-foreground': '#d4d6dc',
      '--color-destructive': '#c45050',
      '--color-destructive-foreground': '#d4d6dc',
      '--color-border': '#3a3c44',
      '--color-input': '#303238',
      '--color-ring': '#8890a0',
      '--color-active-overlay': 'rgba(255, 255, 255, 0.12)',
      '--theme-radius': '8px',
      '--theme-border-width': '1px',
      '--theme-shadow': '0 10px 15px 0 rgba(0, 0, 0, 0.4)',
    },
  },
  {
    id: 'kela',
    name: 'Kela',
    description: 'Neo-Brutalism',
    variant: 'light',
    enableTimelineBorders: true,
    defaultTitleFontId: 'spacemono',
    bodyFontPackId: 'jetbrainsMono',
    tokens: {
      '--color-background': '#fffb00',
      '--color-foreground': '#4a2e1b',
      '--color-card': '#ffffff',
      '--color-card-foreground': '#4a2e1b',
      '--color-popover': '#ffffff',
      '--color-popover-foreground': '#4a2e1b',
      '--color-primary': '#66cc66',
      '--color-primary-foreground': '#4a2e1b',
      '--color-secondary': '#00d5ff',
      '--color-secondary-foreground': '#4a2e1b',
      '--color-muted': '#f0f0f0',
      '--color-muted-foreground': '#555555',
      '--color-accent': '#ff00aa',
      '--color-accent-foreground': '#4a2e1b',
      '--color-destructive': '#ff0000',
      '--color-destructive-foreground': '#ffffff',
      '--color-border': '#000000',
      '--color-input': '#ffffff',
      '--color-ring': '#000000',
      '--color-active-overlay': 'rgba(0, 0, 0, 0.2)',
      /* MUST be exactly '0' (not '0px') for React logic string matching */
      '--theme-radius': '0',
      '--theme-border-width': '3px',
      '--theme-shadow': '4px 4px 0px 0px rgba(0, 0, 0, 1)',
    },
  },
] as const;

export type ThemeDefinition = (typeof THEME_DEFINITIONS)[number];
export type ThemeId = ThemeDefinition['id'];

/** Internal source-of-truth helper; runtime fallback lives in themes.ts */
export function getTitleFontConfig(id: TitleFontId) {
  return TITLE_FONTS.find((font) => font.id === id) ?? TITLE_FONTS[0];
}

export function getBodyFontPack(id: BodyFontPackId) {
  return BODY_FONT_PACKS[id];
}

/** Internal source-of-truth helper; runtime fallback lives in themes.ts */
export function getThemeDefinition(id: ThemeId) {
  return THEME_DEFINITIONS.find((theme) => theme.id === id) ?? THEME_DEFINITIONS[0];
}

export function resolveThemeVariables(theme: ThemeDefinition): Record<string, string> {
  const titleFont = getTitleFontConfig(theme.defaultTitleFontId);
  const bodyFontPack = getBodyFontPack(theme.bodyFontPackId);

  return {
    ...theme.tokens,
    '--font-heading': `'${titleFont.fontFamily}'`,
    '--font-body': `'${bodyFontPack['--font-body']}'`,
    '--font-body-medium': `'${bodyFontPack['--font-body-medium']}'`,
    '--font-body-semibold': `'${bodyFontPack['--font-body-semibold']}'`,
    '--font-body-bold': `'${bodyFontPack['--font-body-bold']}'`,
  };
}
