import '../global.css';

import { useEffect } from 'react';
import { Platform, Text, View } from 'react-native';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { KeyboardProvider } from 'react-native-keyboard-controller';
import { SafeAreaListener } from 'react-native-safe-area-context';
import { Stack } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import * as SplashScreen from 'expo-splash-screen';
import * as SystemUI from 'expo-system-ui';
import { useFonts } from 'expo-font';
import { Uniwind, useCSSVariable } from 'uniwind';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';
import { db } from '~/db';
import migrations from '~/drizzle/migrations';
import { useSettingsStore } from '~/lib/settings';
import {
  getThemeConfig,
  DEFAULT_THEME_ID,
  DEFAULT_THEME_SHEET_RADIUS,
} from '~/lib/theme/themes';
import { AppLoadingScreen } from '~/components/AppLoadingScreen';
import { PortalHost } from '~/components/primitives/portal';
import { Toaster } from '~/components/ui/toast';

// ── Google Fonts ────────────────────────────────────────────────────
import {
  Inter_400Regular,
  Inter_500Medium,
  Inter_600SemiBold,
  Inter_700Bold,
} from '@expo-google-fonts/inter';
import { Figtree_700Bold } from '@expo-google-fonts/figtree';
import { Cinzel_700Bold } from '@expo-google-fonts/cinzel';
import { Merriweather_700Bold } from '@expo-google-fonts/merriweather';
import { Lora_700Bold } from '@expo-google-fonts/lora';
import { SpaceMono_700Bold } from '@expo-google-fonts/space-mono';
import {
  JetBrainsMono_400Regular,
  JetBrainsMono_500Medium,
  JetBrainsMono_600SemiBold,
  JetBrainsMono_700Bold,
} from '@expo-google-fonts/jetbrains-mono';

SplashScreen.preventAutoHideAsync();

// Apply saved theme before React renders to avoid flash
const rawSavedTheme = useSettingsStore.getState().theme || DEFAULT_THEME_ID;
const activeThemeId = getThemeConfig(rawSavedTheme).id;

// Cast needed: uniwind-types.d.ts regenerated by Metro with custom theme names
Uniwind.setTheme(activeThemeId as Parameters<typeof Uniwind.setTheme>[0]);

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // Cache data indefinitely — all mutations and direct DB operations
      // (import, delete-all) explicitly call invalidateQueries(), so the
      // cache stays correct without time-based expiry.  This avoids
      // redundant SQLite reads on every mount/focus and gives instant
      // results for previously-fetched queries (search, timeline, etc.).
      staleTime: Infinity,
    },
  },
});

export default function Layout() {
  const { success, error } = useMigrations(db, migrations);
  const theme = useSettingsStore((s) => s.theme);
  const hasHydrated = useSettingsStore((s) => s._hasHydrated);
  const themeConfig = getThemeConfig(theme);

  const [fontsLoaded, fontsError] = useFonts({
    Inter_400Regular,
    Inter_500Medium,
    Inter_600SemiBold,
    Inter_700Bold,
    Figtree_700Bold,
    Cinzel_700Bold,
    Merriweather_700Bold,
    Lora_700Bold,
    SpaceMono_700Bold,
    JetBrainsMono_400Regular,
    JetBrainsMono_500Medium,
    JetBrainsMono_600SemiBold,
    JetBrainsMono_700Bold,
  });

  const [primaryColor, primaryForeground, backgroundColor, themeRadiusStr] =
    useCSSVariable([
      '--color-primary',
      '--color-primary-foreground',
      '--color-background',
      '--theme-radius',
    ]);

  const sheetCornerRadius =
    String(themeRadiusStr) === '0' ? 0 : DEFAULT_THEME_SHEET_RADIUS;

  const isBootstrapLoading =
    !error && (!success || (!fontsLoaded && !fontsError));

  // Keep native splash until persisted settings (and Uniwind theme) are ready
  useEffect(() => {
    if (hasHydrated || error) {
      SplashScreen.hideAsync();
    }
  }, [hasHydrated, error]);

  // Sync native root background once theme is trustworthy (hydrated), or on migration error
  useEffect(() => {
    if ((hasHydrated || error) && backgroundColor) {
      SystemUI.setBackgroundColorAsync(backgroundColor as string);
    }
  }, [hasHydrated, error, backgroundColor]);

  // Show migration error
  if (error) {
    return (
      <View className="flex-1 items-center justify-center bg-background p-4">
        <Text className="text-destructive text-center">
          Database migration error: {error.message}
        </Text>
      </View>
    );
  }

  // Keep the splash screen visible while loading
  if (!hasHydrated) {
    return null;
  }

  if (isBootstrapLoading) {
    return <AppLoadingScreen />;
  }

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <QueryClientProvider client={queryClient}>
        <SafeAreaListener
          onChange={({ insets }) => {
            Uniwind.updateInsets(insets);
          }}>
          <KeyboardProvider>
            <Stack
              screenOptions={{
                headerShown: false,
                headerTitleAlign: 'center',
                headerTintColor: primaryForeground as string,
                headerStyle: { backgroundColor: primaryColor as string },
                headerTitleStyle: { fontWeight: 'bold' },
              }}>
              <Stack.Screen name="index" />
              <Stack.Screen
                name="gratitudeEntry/index"
                options={{
                  title: 'Gratitude Entry',
                  headerShown: false,
                }}
              />
              <Stack.Screen
                name="gratitudeEntry/[noteId]"
                options={{
                  title: 'Gratitude Entry View',
                  headerShown: false,
                }}
              />
              <Stack.Screen
                name="dateEntries/[dateMs]"
                options={{
                  title: 'Date Entries',
                  headerShown: false,
                }}
              />
              <Stack.Screen
                name="settings"
                options={{
                  title: 'Settings',
                  headerShown: false,
                  presentation: 'formSheet',
                  sheetAllowedDetents: Platform.OS === 'android' ? [0.96] : [0.75, 1],
                  sheetCornerRadius: sheetCornerRadius,
                  sheetGrabberVisible: false,
                }}
              />
            </Stack>
            <StatusBar style={themeConfig.variant === 'dark' ? 'light' : 'dark'} />
            <Toaster />
            <PortalHost />
          </KeyboardProvider>
        </SafeAreaListener>
      </QueryClientProvider>
    </GestureHandlerRootView>
  );
}
