const { withProjectBuildGradle } = require('expo/config-plugins');

const MARKER = '// @generated by withGoogleAuthorization';
const DEPENDENCY_BLOCK = `${MARKER}
subprojects { subproject ->
    // Expo mirrors Kotlin inline modules into :expo, so their third-party
    // compile dependencies must be attached to that module rather than :app.
    if (subproject.name == "expo") {
        subproject.pluginManager.withPlugin("com.android.library") {
            subproject.dependencies.add(
                "implementation",
                "com.google.android.gms:play-services-auth:21.6.0"
            )
        }
    }
}`;

module.exports = function withGoogleAuthorization(config) {
  return withProjectBuildGradle(config, (mod) => {
    if (mod.modResults.language !== 'groovy') {
      throw new Error('Google authorization plugin currently requires Groovy Gradle');
    }
    if (!mod.modResults.contents.includes(MARKER)) {
      mod.modResults.contents = `${mod.modResults.contents.trim()}\n\n${DEPENDENCY_BLOCK}\n`;
    }
    return mod;
  });
};
